<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Dynamic Blazor Component Loader</Title>
    <Authors>Carl Franklin</Authors>
    <Company>App vNext, LLC</Company>
    <Description>A .NET Library that lets you replace Blazor Components (RCLs) in place at runtime.</Description>
    <Copyright>Copyright © 2024 by App vNext, LLC</Copyright>
    <RepositoryUrl>https://github.com/carlfranklin/DynamicBlazorComponentLoader</RepositoryUrl>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
  </ItemGroup>

</Project>
